# Generated by Django 4.0.2 on 2022-03-16 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.IntegerField(choices=[(1, 'Mohabolipur'), (2, 'Suvra'), (3, 'Kornai'), (4, 'BKSP')])),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('cooking_system', models.IntegerField(choices=[(1, 'Meal'), (2, 'Bati'), (3, 'On Your Own')])),
                ('structure', models.IntegerField(choices=[(1, 'Multi-storey'), (2, 'Single-storey'), (3, 'Tin Shed')])),
                ('students_num', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=14, unique=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=150)),
                ('id_card_pic', models.ImageField(blank=True, upload_to='')),
                ('fb_profile', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.IntegerField()),
                ('bed_num', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('price', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Not Available'), (1, 'Available')], default=0)),
                ('picture', models.ImageField(upload_to='')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.mess')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nid_card_pic', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mess',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.owner'),
        ),
    ]
