# Generated by Django 4.0.2 on 2022-03-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Room_Gallery')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.room')),
            ],
        ),
    ]
