# Generated by Django 4.0.2 on 2022-03-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_room_status_roomimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='room',
            name='picture',
        ),
        migrations.CreateModel(
            name='MessImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Mess_Gallery')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.mess')),
            ],
        ),
    ]
