# Generated by Django 4.0.2 on 2022-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='cooking_system',
            new_name='meal_system',
        ),
        migrations.AlterField(
            model_name='mess',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
