# Generated by Django 4.0.2 on 2022-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_cooking_system_mess_meal_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='address',
            field=models.CharField(default='Default Mess Address', max_length=500),
        ),
    ]
