# Generated by Django 4.0.2 on 2022-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_mess_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=14),
        ),
    ]
