# Generated by Django 4.0.2 on 2022-05-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
