# Generated by Django 4.0.2 on 2022-05-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_rename_user_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.owner'),
        ),
    ]
